apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-blockchain-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 40Gi
